services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: initiare-caddy
    hostname: initiare_caddy
    networks:
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/config/:/etc/caddy/
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: initiare-backend
    hostname: initiare_backend
    networks:
      - db_network
      - redis_network
      - backend_network
    depends_on:
      - db
      - redis
    volumes:
      - go_mod_cache:/go/pkg/mod
      - go_build_cache:/root/.cache/go-build

  db:
    image: postgres:alpine
    container_name: initiare-db
    hostname: initiare_db
    env_file:
      - ./env/postgres.env
    networks: 
      - db_network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: initiare-redis
    hostname: initiare_redis
    networks:
      - redis_network
    restart: unless-stopped

volumes:
  db_data:
  go_build_cache:
  go_mod_cache:

networks:
  db_network:
  redis_network:
  backend_network: